# Generated by Django 5.0.7 on 2024-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_customuser_bio_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="session_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
