# Generated by Django 5.0.7 on 2024-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatmessage_session_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="session_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
